import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import FooterController from "@/components/shared/FooterController/FooterController";
import ScrollTopToButton from "@/components/shared/ScrollTopToButton/ScrollTopToButton";
import { AosProvider } from "@/components/AosProvider/AosProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Travel Tour Teacher",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased overflow-x-hidden`}
      >
        <AosProvider>
          <Navbar />
          {children}
          <ScrollTopToButton />
          <FooterController />
        </AosProvider>
      </body>
    </html>
  );
}
